### PR TITLE
Add support for Django 1.9

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by mauricioabreu** [comment]
For anyone interested in having this cool project to be supported with Django 1.9, please, give me some feedback. :-) Thanks!

**Comment by Alphare** [comment]
Very nice! I would absolutely love to see this implemented.

**Comment by mauricioabreu** [comment]
It would be nice to have a tox setup running for this library.
I tested version by version manually. But a tox configuration would be a new pull request. Travis is a good thing too.

**Comment by techdragon** [comment]
It would be nice if we also had Travis CI running on the project. Also, this would fix #4

**Comment by adrianmo** [comment]
I run into the same issue with Django 1.9 and this PR fixes it. It should be merged.

**Comment by blikjeham** [comment]
It has been over a year since this pull request was made. Please merge this fix to allow support for Django >= 1.9!

**Comment by werthen** [comment]
Please merge this!

**Pull request merged**
