### PR TITLE
loading url from template.defaulttags, for django 1.9+

### LINKED ISSUE #4: Invalid template library for django >= 1.9rc1
when using with django 1.9 rc1:
```
Invalid template library specified. ImportError raised when trying to load 'activelink.templatetags.activelink': cannot import name url
```

ImportError is raised by https://github.com/j4mie/django-activelink/blob/master/activelink/templatetags/activelink.py#L3

`url` templatetag now lives in `django.template.defaulttags`

### PR DESCRIPTION
**Pull request by bianchimro**
closes #4

### CODE REVIEW

**Comment by illagrenan** [comment]
+1 for this PR

**Comment by j4mie** [comment]
This isn't actually enough - the tests don't come close to passing on 1.9. I'm looking at it at the moment.

**Comment by Alphare** [comment]
@j4mie How are things going regarding this issue? I would love to update to django 1.9 in the somewhat near future.

**Comment by mauricioabreu** [comment]
Sorry if I did something wrong but I have just created a new pull request regarding to Django 1.9 support. 
I tested using several Django versions: from 1.3.X to 1.9.X

Here is the pull request: https://github.com/j4mie/django-activelink/pull/6

**Pull request closed without merging**
